In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/df-prep-fixed/df_prep (1).csv


In [2]:
df = pd.read_csv('/kaggle/input/df-prep-fixed/df_prep (1).csv',encoding='utf-8')
df.columns

Index(['Unnamed: 0', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours', 'Month', 'WeekDay', 'Year'],
      dtype='object')

In [3]:
df = df.drop(['Unnamed: 0'],axis=1)
df

Reason_1  Reason_2  Reason_3  Reason_4        Date  \
0       False     False     False      True  2015-07-07   
1       False     False     False     False  2015-07-14   
2       False     False     False      True  2015-07-15   
3        True     False     False     False  2015-07-16   
4       False     False     False      True  2015-07-23   
..        ...       ...       ...       ...         ...   
695      True     False     False     False  2018-05-23   
696      True     False     False     False  2018-05-23   
697      True     False     False     False  2018-05-24   
698     False     False     False      True  2018-05-24   
699     False     False     False      True  2018-05-31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Month  WeekDay  Year  
0        7        1  2015  
1        7        1  2015  
2        7        2  2015  
3        7        3  2015  
4        7        3  2015  
..     ...      ...   ...  
695      5        2  2018  
696      5        2  2018  
697      5        3  2018  
698      5        3  2018  
699      5        3  2018  

[700 rows x 17 columns]

In [4]:
df['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(df['Absenteeism Time in Hours'] > 
                   df['Absenteeism Time in Hours'].median(),1, 0)


In [6]:
df['Excessive Absenteeism'] = targets
df

Reason_1  Reason_2  Reason_3  Reason_4        Date  \
0       False     False     False      True  2015-07-07   
1       False     False     False     False  2015-07-14   
2       False     False     False      True  2015-07-15   
3        True     False     False     False  2015-07-16   
4       False     False     False      True  2015-07-23   
..        ...       ...       ...       ...         ...   
695      True     False     False     False  2018-05-23   
696      True     False     False     False  2018-05-23   
697      True     False     False     False  2018-05-24   
698     False     False     False      True  2018-05-24   
699     False     False     False      True  2018-05-31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Month  WeekDay  Year  Excessive Absenteeism  
0        7        1  2015                      1  
1        7        1  2015                      0  
2        7        2  2015                      0  
3        7        3  2015                      1  
4        7        3  2015                      0  
..     ...      ...   ...                    ...  
695      5        2  2018                      1  
696      5        2  2018                      0  
697      5        3  2018                      1  
698      5        3  2018                      0  
699      5        3  2018                      0  

[700 rows x 18 columns]

In [7]:
df = df[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Month','WeekDay','Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours','Excessive Absenteeism']]

In [8]:
#sprawdzamy rozkład danych excessive_absenteeism: cutoff:mediana -->stosunek 0 do 1 powinien być w granicach 0,4-0,6
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
#checkpoint= preprocessing data 
data_with_targets = df.drop(['Absenteeism Time in Hours','WeekDay','Daily Work Load Average','Distance to Work'],axis=1)
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  \
0       False     False     False      True      7                     289   
1       False     False     False     False      7                     118   
2       False     False     False      True      7                     179   
3        True     False     False     False      7                     279   
4       False     False     False      True      7                     289   
..        ...       ...       ...       ...    ...                     ...   
695      True     False     False     False      5                     179   
696      True     False     False     False      5                     225   
697      True     False     False     False      5                     330   
698     False     False     False      True      5                     235   
699     False     False     False      True      5                     291   

     Age  Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0     33               30          0         2     1                      1  
1     50               31          0         1     0                      0  
2     38               31          0         0     0                      0  
3     39               24          0         2     0                      1  
4     33               30          0         2     1                      0  
..   ...              ...        ...       ...   ...                    ...  
695   40               22          1         2     0                      1  
696   28               24          0         1     2                      0  
697   28               25          1         0     0                      1  
698   32               25          1         0     0                      0  
699   40               25          0         1     1                      0  

[700 rows x 12 columns]

In [10]:
df is data_with_targets

False

In [11]:
data_with_targets.shape

(700, 12)

In [12]:
# .iloc: [row indices,column indices] -isolating the target column: excessive absenteeism
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  \
0       False     False     False      True      7                     289   
1       False     False     False     False      7                     118   
2       False     False     False      True      7                     179   
3        True     False     False     False      7                     279   
4       False     False     False      True      7                     289   
..        ...       ...       ...       ...    ...                     ...   
695      True     False     False     False      5                     179   
696      True     False     False     False      5                     225   
697      True     False     False     False      5                     330   
698     False     False     False      True      5                     235   
699     False     False     False      True      5                     291   

     Age  Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0     33               30          0         2     1                      1  
1     50               31          0         1     0                      0  
2     38               31          0         0     0                      0  
3     39               24          0         2     0                      1  
4     33               30          0         2     1                      0  
..   ...              ...        ...       ...   ...                    ...  
695   40               22          1         2     0                      1  
696   28               24          0         1     2                      0  
697   28               25          1         0     0                      1  
698   32               25          1         0     0                      0  
699   40               25          0         1     1                      0  

[700 rows x 12 columns]

In [13]:
#scaling preparation-Standardization
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [14]:
#from sklearn.preprocessing import StandardScaler
#abs_scaler = StandardScaler()
#applied standardizaiton: substracting mean and division by standard deviation 

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    
    def __init__(self,columns):
        
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    
    def fit(self, X, y=None):
        self.scaler = StandardScaler()
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    

    def transform(self, X, y=None, copy=None):
        
        init_col_order = X.columns
        
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
#columns_to_scale = [ 'Month', 'WeekDay',
       #'Transportation Expense', 'Distance to Work', 'Age',
       #'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']
        
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
columns_to_scale

['Month',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [20]:
abs_scaler = CustomScaler(columns_to_scale)

In [21]:
#collecting standardization information: mean and stdev
#naprawione przez:https://stackoverflow.com/questions/70587280/sklearn-attributeerror-customscaler-object-has-no-attribute-copy
abs_scaler.fit(unscaled_inputs)

/opt/conda/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

abs_scaler

In [22]:
#StandardScaler are compatible with pandas, but such transformations switches from pandas to ndarray
scaled_inputs = abs_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
0       False     False     False      True  0.182726                1.005844   
1       False     False     False     False  0.182726               -1.574681   
2       False     False     False      True  0.182726               -0.654143   
3        True     False     False     False  0.182726                0.854936   
4       False     False     False      True  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695      True     False     False     False -0.388293               -0.654143   
696      True     False     False     False -0.388293                0.040034   
697      True     False     False     False -0.388293                1.624567   
698     False     False     False      True -0.388293                0.190942   
699     False     False     False      True -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [24]:
#splitting and shuffling the data:
from sklearn.model_selection import train_test_split

In [25]:
#targets: excessive absenteeism
#inputs: the rest  
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
 303     False     False     False     False  1.039256                0.190942   
 182      True     False     False     False -0.959313                0.387122   
 174     False     False     False      True -0.959313                0.040034   
 249     False     False      True     False  0.182726                1.005844   
 685     False     False     False      True -0.388293               -1.574681   
 ..        ...       ...       ...       ...       ...                     ...   
 537     False     False     False      True  1.324766                1.005844   
 298     False     False     False      True  1.039256               -0.654143   
 483     False     False     False      True  0.468236               -1.574681   
 95      False     False     False      True  1.324766                0.040034   
 584     False     False     False      True -1.530333               -0.654143   
 
           Age

In [26]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size =0.8,random_state=1)

In [27]:
print(x_train.shape,x_test.shape)

(560, 11) (140, 11)


In [28]:
#Model training and its evaluation
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train,y_train)

LogisticRegression()

In [31]:
reg.score(x_train,y_train)

0.7732142857142857

In [32]:
#building score method manually[!!!!]
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,

In [33]:
y_train

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,

In [34]:
#comparison of model prediction with y_train
np.sum(model_outputs == y_train)

433

In [35]:
model_outputs.shape

(560,)

In [36]:
score = np.sum(model_outputs == y_train)/model_outputs.shape[0]
score

0.7732142857142857

In [37]:
#estimating the intercept and the coefficients 
#log(odds) = b0 +b1x1+b2x2 etc... b0:intercept, bn: coefficients


In [38]:
#getting intercept
reg.intercept_

array([-1.69437685])

In [39]:
#getting coeffs
reg.coef_

array([[ 2.80404409,  0.99656162,  3.10189616,  0.84644083,  0.10652555,
         0.57203993, -0.25110668,  0.28498896, -0.04585548,  0.46513821,
        -0.292372  ]])

In [40]:
feature_names = unscaled_inputs.columns.values

In [41]:
summary_tab = pd.DataFrame (columns=['Feature_name'],data=feature_names)
summary_tab['Coefficient'] = np.transpose(reg.coef_)
summary_tab

Feature_name  Coefficient
0                 Reason_1     2.804044
1                 Reason_2     0.996562
2                 Reason_3     3.101896
3                 Reason_4     0.846441
4                    Month     0.106526
5   Transportation Expense     0.572040
6                      Age    -0.251107
7          Body Mass Index     0.284989
8                Education    -0.045855
9                 Children     0.465138
10                    Pets    -0.292372

In [42]:
summary_tab.index = summary_tab.index + 1 

In [43]:
summary_tab.loc[0] = ['Intercept',reg.intercept_[0]]

In [44]:
summary_tab = summary_tab.sort_index()
summary_tab

Feature_name  Coefficient
0                Intercept    -1.694377
1                 Reason_1     2.804044
2                 Reason_2     0.996562
3                 Reason_3     3.101896
4                 Reason_4     0.846441
5                    Month     0.106526
6   Transportation Expense     0.572040
7                      Age    -0.251107
8          Body Mass Index     0.284989
9                Education    -0.045855
10                Children     0.465138
11                    Pets    -0.292372

In [45]:
summary_tab['Odds_ratio'] = np.exp(summary_tab.Coefficient)
summary_tab

Feature_name  Coefficient  Odds_ratio
0                Intercept    -1.694377    0.183714
1                 Reason_1     2.804044   16.511285
2                 Reason_2     0.996562    2.708951
3                 Reason_3     3.101896   22.240082
4                 Reason_4     0.846441    2.331334
5                    Month     0.106526    1.112406
6   Transportation Expense     0.572040    1.771878
7                      Age    -0.251107    0.777939
8          Body Mass Index     0.284989    1.329747
9                Education    -0.045855    0.955180
10                Children     0.465138    1.592234
11                    Pets    -0.292372    0.746491

In [46]:
summary_tab.sort_values('Odds_ratio',ascending=False)

Feature_name  Coefficient  Odds_ratio
3                 Reason_3     3.101896   22.240082
1                 Reason_1     2.804044   16.511285
2                 Reason_2     0.996562    2.708951
4                 Reason_4     0.846441    2.331334
6   Transportation Expense     0.572040    1.771878
10                Children     0.465138    1.592234
8          Body Mass Index     0.284989    1.329747
5                    Month     0.106526    1.112406
9                Education    -0.045855    0.955180
7                      Age    -0.251107    0.777939
11                    Pets    -0.292372    0.746491
0                Intercept    -1.694377    0.183714

In [47]:
#Checkpoint: simplyfying model

In [48]:
#testing the regression model 

In [49]:
reg.score(x_test,y_test)

0.75

In [50]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.26316067, 0.73683933],
       [0.75352471, 0.24647529],
       [0.75263033, 0.24736967],
       [0.8504347 , 0.1495653 ],
       [0.56074809, 0.43925191],
       [0.87577811, 0.12422189],
       [0.33003037, 0.66996963],
       [0.15332554, 0.84667446],
       [0.76464709, 0.23535291],
       [0.13406616, 0.86593384],
       [0.70561623, 0.29438377],
       [0.13745303, 0.86254697],
       [0.61342902, 0.38657098],
       [0.32918386, 0.67081614],
       [0.35397769, 0.64602231],
       [0.84266371, 0.15733629],
       [0.76922364, 0.23077636],
       [0.38109653, 0.61890347],
       [0.86179186, 0.13820814],
       [0.79262112, 0.20737888],
       [0.70561623, 0.29438377],
       [0.51066833, 0.48933167],
       [0.44532234, 0.55467766],
       [0.64823281, 0.35176719],
       [0.51842515, 0.48157485],
       [0.83350224, 0.16649776],
       [0.71189416, 0.28810584],
       [0.75912973, 0.24087027],
       [0.87061106, 0.12938894],
       [0.62715666, 0.37284334],
       [0.

In [51]:
predicted_proba[:,1]

array([0.73683933, 0.24647529, 0.24736967, 0.1495653 , 0.43925191,
       0.12422189, 0.66996963, 0.84667446, 0.23535291, 0.86593384,
       0.29438377, 0.86254697, 0.38657098, 0.67081614, 0.64602231,
       0.15733629, 0.23077636, 0.61890347, 0.13820814, 0.20737888,
       0.29438377, 0.48933167, 0.55467766, 0.35176719, 0.48157485,
       0.16649776, 0.28810584, 0.24087027, 0.12938894, 0.37284334,
       0.80318681, 0.43063412, 0.50142346, 0.48593664, 0.78925488,
       0.37998217, 0.32455061, 0.19998034, 0.22015543, 0.4231932 ,
       0.25307551, 0.77273996, 0.26870682, 0.85732736, 0.5618781 ,
       0.64949164, 0.74972423, 0.6390368 , 0.79352782, 0.20988993,
       0.23535291, 0.24736967, 0.23621958, 0.81695533, 0.13807313,
       0.19998034, 0.12769491, 0.23535291, 0.25216741, 0.23621958,
       0.26277255, 0.64602231, 0.63552123, 0.85732736, 0.47698424,
       0.74101904, 0.72065836, 0.36082704, 0.30031878, 0.13449326,
       0.22542155, 0.28810584, 0.19515881, 0.87122434, 0.66659

In [52]:
#Saving the logreg model- creating a file that will store the model information and its training

In [53]:
#pickling
import pickle
with open('mlmodel','wb') as file:
    pickle.dump(reg, file)
with open('abscaler','wb') as scalerfile:
    pickle.dump(abs_scaler, scalerfile)